import Link from "next/link";
import { ArrowLeft, ArrowRight, Shield, Zap, Search, FileCheck } from "lucide-react";

export default function DigitalSignaturesPage() {
    return (
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-1000">
            <div className="flex items-center gap-4 mb-4">
                <span className="flex items-center justify-center w-8 h-8 rounded bg-primary/20 text-primary font-bold font-mono text-sm border border-primary/30">08</span>
                <h4 className="text-foreground/60 font-mono tracking-widest uppercase m-0">Module 8 — Digital Signatures</h4>
            </div>

            <h1 className="text-4xl md:text-5xl font-bold mb-8">Digital Signatures: The Verification Pipeline</h1>

            <p className="lead text-xl text-muted-foreground border-l-4 border-primary pl-4 py-2 not-prose">
                A digital signature is the digital equivalent of a handwritten signature or stamped seal, but far more secure. It provides <strong>Authentication</strong>, <strong>Integrity</strong>, and <strong>Non-repudiation</strong>.
            </p>

            <h2>🛡️ The Core Principles</h2>
            <ul className="list-disc pl-6 space-y-4 my-8 text-foreground/80">
                <li><strong>Authentication</strong>: Proves the message was created by a specific sender.</li>
                <li><strong>Integrity</strong>: Proves the message was not altered in transit.</li>
                <li><strong>Non-repudiation</strong>: The sender cannot later deny having signed the message (thanks to the private key being secret).</li>
            </ul>

            <div className="not-prose bg-accent/5 border border-accent/20 p-8 rounded-3xl my-16 group relative overflow-hidden shadow-2xl dark:shadow-black/40">
                <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity">
                    <Shield size={180} />
                </div>
                <h3 className="text-2xl font-bold font-mono text-foreground dark:text-white mb-6 flex items-center gap-3">
                    <FileCheck className="text-accent" size={24} /> The Verification Blueprint
                </h3>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-12 relative z-10">
                    <div className="space-y-6">
                        <h4 className="text-accent font-mono text-xs uppercase font-bold tracking-widest">Logic Flow</h4>
                        <div className="space-y-4">
                            <div className="flex gap-4">
                                <div className="w-8 h-8 rounded-full bg-accent/20 text-accent flex items-center justify-center shrink-0 font-bold text-xs italic">1</div>
                                <div>
                                    <h5 className="font-bold text-xs uppercase text-foreground dark:text-white mb-1">Decryption Pass</h5>
                                    <p className="text-[10px] text-muted-foreground leading-relaxed">
                                        The signature is decrypted using the sender's <strong>Public Key</strong>. This reveals the "Original Hash" that was generated by the sender.
                                    </p>
                                </div>
                            </div>
                            <div className="flex gap-4">
                                <div className="w-8 h-8 rounded-full bg-accent/20 text-accent flex items-center justify-center shrink-0 font-bold text-xs italic">2</div>
                                <div>
                                    <h5 className="font-bold text-xs uppercase text-foreground dark:text-white mb-1">Local Hash Generation</h5>
                                    <p className="text-[10px] text-muted-foreground leading-relaxed">
                                        The recipient takes the received message and calculates a <strong>New Hash</strong> using the same algorithm (e.g., SHA-256).
                                    </p>
                                </div>
                            </div>
                            <div className="flex gap-4">
                                <div className="w-8 h-8 rounded-full bg-accent/20 text-accent flex items-center justify-center shrink-0 font-bold text-xs italic">3</div>
                                <div>
                                    <h5 className="font-bold text-xs uppercase text-foreground dark:text-white mb-1">Collision Match</h5>
                                    <p className="text-[10px] text-muted-foreground leading-relaxed">
                                        The Original Hash and the New Hash are compared. If even one bit differs, the signature is invalid.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="bg-black/60 p-6 rounded-2xl border border-accent/20 flex flex-col justify-center">
                        <h5 className="text-xs font-bold text-foreground dark:text-white mb-4 uppercase tracking-[0.2em] text-center">Implementation Math</h5>
                        <div className="font-mono text-[10px] text-accent/80 space-y-2 mb-6">
                            <p>// Client-Side Verification:</p>
                            <p>const isValid = crypto.subtle.verify(&#123;</p>
                            <p className="pl-4">name: "RSA-PSS",</p>
                            <p className="pl-4">saltLength: 32</p>
                            <p>&#125;, publicKey, signature, data);</p>
                        </div>

                        <div className="pt-4 border-t border-white/10 space-y-3">
                            <h5 className="text-[10px] font-bold text-foreground dark:text-white uppercase tracking-widest text-center">Verification Weights</h5>
                            <div className="space-y-2">
                                <div className="flex justify-between text-[8px] uppercase font-bold text-muted-foreground">
                                    <span>Signed JSON (2KB)</span>
                                    <span className="text-primary">~0.1ms</span>
                                </div>
                                <div className="h-1 bg-muted rounded-full overflow-hidden"><div className="h-full bg-primary w-[2%]" /></div>

                                <div className="flex justify-between text-[8px] uppercase font-bold text-muted-foreground">
                                    <span>Binary Firmware (5MB)</span>
                                    <span className="text-yellow-400">~15ms</span>
                                </div>
                                <div className="h-1 bg-muted rounded-full overflow-hidden"><div className="h-full bg-yellow-400 w-[45%]" /></div>
                            </div>
                            <p className="text-[7px] text-center text-muted-foreground italic">
                                RSA verification is extremely fast because the public exponent (e) is usually small (e=65537), requiring only a few modular multiplications.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div className="not-prose bg-muted/10 border border-border p-8 rounded-3xl my-12">
                <h3 className="text-xl font-bold font-mono text-foreground dark:text-white mb-4 flex items-center gap-2">
                    <Search size={20} className="text-accent" /> Why Hashing First?
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                    Asymmetric encryption (RSA) is mathematically heavy and extremely slow. If we tried to encrypt a 10MB file directly with a private key, it could take minutes. By hashing the 10MB file into a 32-byte string first, and only signing that 32-byte string, we maintain security while increasing speed by <strong>100,000x</strong>.
                </p>
            </div>

            <hr className="my-12 border-border" />

            <div className="not-prose flex justify-between">
                <Link href="/learn/diffie-hellman" className="group flex items-center gap-3 text-muted-foreground hover:text-foreground transition-colors px-4 py-2">
                    <ArrowLeft className="group-hover:-translate-x-1 transition-transform" /> Back: Diffie-Hellman
                </Link>
                <Link href="/learn/jwt-studio" className="group flex items-center gap-3 bg-primary text-black px-6 py-3 rounded-md font-bold hover:bg-primary/90 transition-colors">
                    Next: JWT Studio <ArrowRight className="group-hover:translate-x-1 transition-transform" />
                </Link>
            </div>
        </div>
    );
}
